/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mis_tipos.h"

bool_t
xdr_Texto (XDR *xdrs, Texto *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Lista (XDR *xdrs, Lista *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dato))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (Lista), (xdrproc_t) xdr_Lista))
		 return FALSE;
	return TRUE;
}
