/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MIS_TIPOS_H_RPCGEN
#define _MIS_TIPOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *Texto;

struct Lista {
	int dato;
	struct Lista *siguiente;
};
typedef struct Lista Lista;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Texto (XDR *, Texto*);
extern  bool_t xdr_Lista (XDR *, Lista*);

#else /* K&R C */
extern bool_t xdr_Texto ();
extern bool_t xdr_Lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MIS_TIPOS_H_RPCGEN */
